#! /usr/bin/env node

function getFeatureFiles(logLines) {
    const featureLines = logLines.filter((line) => line.includes("# features"));
    const featureFiles = featureLines.map(line => line.match(/(features.*)/)[1])

    return featureFiles;
}

const data = [
    "Running with gitlab-runner 15.1.0 (76984217)",
    "  on ecni-runner sLxAtHdc",
    "  feature flags: FF_NETWORK_PER_BUILD:true, FF_USE_FASTZIP:true",
    "Using Docker executor with image 943810802074.dkr.ecr.eu-west-1.amazonaws.com/ecni-cicd:feat-2677-as-a-developer-fix-failing-tests-in-ci ...",
    "Starting service postgres:15.0 ...",
    "Pulling docker image postgres:15.0 ...",
    "Using docker image sha256:027eba2e89396946fd63dd69c919844b248c8b591c07545321de3006503cc974 for postgres:15.0 with digest postgres@sha256:bab8d7be6466e029f7fa1e69ff6aa0082704db330572638fd01f2791824774d8 ...",
    "Starting service redis:7-alpine ...",
    "Pulling docker image redis:7-alpine ...",
    "Using docker image sha256:0b405767398cb7b7819c57db42c64b7008a4ff174a83e2b639185eff20be1d38 for redis:7-alpine with digest redis@sha256:cbcf5bfbc3eaa232b1fa99e539459f46915a41334d46b54bf894f8837a7f071e ...",
    "WARNING: Service redis:7-alpine is already created. Ignoring.",
    "Starting service mysql:5.6 ...",
    "Pulling docker image mysql:5.6 ...",
    "Using docker image sha256:dd3b2a5dcb48ff61113592ed5ddd762581be4387c7bc552375a2159422aa6bf5 for mysql:5.6 with digest mysql@sha256:20575ecebe6216036d25dab5903808211f1e9ba63dc7825ac20cb975e34cfcae ...",
    "WARNING: Service mysql:5.6 is already created. Ignoring.",
    "Waiting for services to be up and running (timeout 30 seconds)...",
    'Using locally found image version due to "if-not-present" pull policy',
    "Using docker image sha256:cc69a9858c8494fc9d9249794c8c6106f4a218449093ab319f1c7e044336bdf7 for 943810802074.dkr.ecr.eu-west-1.amazonaws.com/ecni-cicd:feat-2677-as-a-developer-fix-failing-tests-in-ci with digest 943810802074.dkr.ecr.eu-west-1.amazonaws.com/ecni-cicd@sha256:40f9bfbcb8f8f9e4339b540834f69c81b71717b0608f79b080afd91154808527 ...",
    "Running on runner-slxathdc-project-37491007-concurrent-0 via ip-172-31-13-225...",
    "Fetching changes with git depth set to 1...",
    "Reinitialized existing Git repository in /builds/ecni-v2/api-v2/.git/",
    "Auto packing the repository in background for optimum performance.",
    'See "git help gc" for manual housekeeping.',
    "Checking out 17f2333c as refs/merge-requests/962/head...",
    "Removing .phpunit.result.cache",
    "Removing node_modules/",
    "Removing public/bundles/",
    "Removing vendor-bin/deptrac/vendor/",
    "Removing vendor-bin/php-codesniffer/vendor/",
    "Removing vendor-bin/php-cs-fixer/vendor/",
    "Removing vendor-bin/php-deprecation-detector/vendor/",
    "Removing vendor-bin/phpcpd/vendor/",
    "Removing vendor-bin/phpinsights/vendor/",
    "Removing vendor-bin/phploc/vendor/",
    "Removing vendor-bin/phpmd/vendor/",
    "Removing vendor-bin/phpmetrics/vendor/",
    "Removing vendor-bin/phpmnd/vendor/",
    "Removing vendor-bin/phpstan/vendor/",
    "Removing vendor/",
    "Skipping Git submodules setup",
    "Downloading artifacts for build (4251625981)...",
    "Downloading artifacts from coordinator... ok      ",
    "  id",
    "=4251625981 responseStatus",
    "=200 OK token",
    "=64_49XPV",
    "Using docker image sha256:cc69a9858c8494fc9d9249794c8c6106f4a218449093ab319f1c7e044336bdf7 for 943810802074.dkr.ecr.eu-west-1.amazonaws.com/ecni-cicd:feat-2677-as-a-developer-fix-failing-tests-in-ci with digest 943810802074.dkr.ecr.eu-west-1.amazonaws.com/ecni-cicd@sha256:40f9bfbcb8f8f9e4339b540834f69c81b71717b0608f79b080afd91154808527 ...",
    "$ make -f Makefile.test jwt-keypair",
    "mkdir -p var/keypair",
    "openssl genrsa -out var/keypair/private.pem 4096",
    "openssl rsa -pubout -in var/keypair/private.pem -out var/keypair/public.pem",
    "writing RSA key",
    "$ make -f Makefile.test aws-keypair",
    "mkdir -p var/aws_credentials",
    "openssl genrsa -out var/aws_credentials/private.pem 2048",
    "openssl rsa -pubout -in var/aws_credentials/private.pem -out var/aws_credentials/public.pem",
    "writing RSA key",
    "$ make -f Makefile.test reset-tests-db",
    "php -d memory_limit=-1 bin/console doctrine:database:drop --env=test --if-exists --force",
    'Dropped database "ecni" for connection named default',
    "php -d memory_limit=-1 bin/console doctrine:database:create --env=test",
    'Created database "ecni" for connection named default',
    "php -d memory_limit=-1 bin/console doctrine:schema:create --env=test",
    " ! [CAUTION] This operation should not be executed in a production environment! ",
    " Creating database schema...",
    " [OK] Database schema created successfully!                                     ",
    "$ make -f Makefile.test behat-http",
    "php -d memory_limit=-1 ./vendor/bin/behat --suite=http --tags '~@databaseMigration' -f progress --stop-on-failure",
    "...................................................................... 70",
    "...................................................................... 140",
    "...................................................................... 210",
    "...................................................................... 280",
    "...................................................................... 350",
    "...................................................................... 420",
    "...................................................................... 490",
    "...................................................................... 560",
    "...................................................................... 630",
    "...................................................................... 700",
    "...................................................................... 770",
    "...................................................................... 840",
    "...................................................................... 910",
    "...................................................................... 980",
    "...................................................................... 1050",
    "...................................................................... 1120",
    "...................................................................... 1190",
    "...................................................................... 1260",
    ".......P.........P..........P..........P..........P.........P......... 1330",
    "...................................................................... 1400",
    ".............P............P............P............P...........P..... 1470",
    "..............................................P...........P........... 1540",
    "...................................................................... 1610",
    ".............................P..........................P............. 1680",
    ".P.......................................................P............ 1750",
    "..............P..............P........................................ 1820",
    "......................................P..............P..............P. 1890",
    "...................................................................... 1960",
    "............P-...........P-........................................... 2030",
    "........................................P...........P................. 2100",
    "...........................P...........P.............................. 2170",
    "...................................................................... 2240",
    ".P.................................................................... 2310",
    ".........................................P............................ 2380",
    "...................................................................... 2450",
    "...................................................................... 2520",
    "...................................................................... 2590",
    "...................................................................... 2660",
    "...................................................................... 2730",
    "...................................................................... 2800",
    "...................................................................... 2870",
    "...................................................................... 2940",
    "...................................................................... 3010",
    "...................................................................... 3080",
    "...................................................................... 3150",
    "...................................................P.................. 3220",
    "...................................................................... 3290",
    "...................................................................... 3360",
    "..........................P........................................... 3430",
    "...................................................................... 3500",
    "...................................................................... 3570",
    "...................................................................... 3640",
    "...................................................................... 3710",
    "...................................................................... 3780",
    "...................................................................... 3850",
    "...................................................................... 3920",
    ".........P.........................P.................................. 3990",
    "...................................................................... 4060",
    "...................................................................... 4130",
    "...................................................................... 4200",
    "...................................................................... 4270",
    "................P-..............P-.................................... 4340",
    "....................................................................P- 4410",
    "...............P-..................................................... 4480",
    "................................................P.....P............... 4550",
    "...................................................................... 4620",
    "...................................................................... 4690",
    ".........................P............................................ 4760",
    "...................................................................... 4830",
    ".......................................................P-............. 4900",
    ".P-..............P-................................................... 4970",
    "...................................................................... 5040",
    "................P-...........P-....................................... 5110",
    "............................P............P............................ 5180",
    "...................................................................... 5250",
    "...................................................................... 5320",
    "...................................................................... 5390",
    "..P-..............P-...................P.............................. 5460",
    "...................................................................... 5530",
    "...................................................................... 5600",
    "................P-.............P-..................................... 5670",
    "...................................................................... 5740",
    "...................................................................... 5810",
    "...................................................................... 5880",
    "...................................................................... 5950",
    "............................P..............P.......................... 6020",
    "...................................................................... 6090",
    ".........................................................P............ 6160",
    "....P................................................................. 6230",
    "................................P.................P................... 6300",
    "...................................................................... 6370",
    "........................................P............................. 6440",
    "...................................................................... 6510",
    "........................................................P............. 6580",
    "...................................................................... 6650",
    "...................................................................... 6720",
    "...................................................................... 6790",
    "...................................................................... 6860",
    "................P..................................................... 6930",
    "...P....................................................P.........P... 7000",
    "......P.........P.........P........................................... 7070",
    "...................................................................... 7140",
    "...................................................................... 7210",
    "...................................................................... 7280",
    "...................................................................... 7350",
    "...................................................................... 7420",
    "...................................................................... 7490",
    "...................................................................... 7560",
    "...................................................................... 7630",
    "...................................................................... 7700",
    "...................................................................... 7770",
    "...................................................................... 7840",
    "...................................................................... 7910",
    "...................................................................... 7980",
    "...................................................................... 8050",
    "...................................................................... 8120",
    "...................................................................... 8190",
    "...................................................................... 8260",
    "...................................................................... 8330",
    "...................................................................... 8400",
    "...................................................................... 8470",
    "...................................................................... 8540",
    "...................................................................... 8610",
    "....................................P................................. 8680",
    "...................P.................................................. 8750",
    "......................................................P.............P. 8820",
    "............P......................................................... 8890",
    "...................................................................... 8960",
    "...................................................................... 9030",
    "...................................................................... 9100",
    "...................................................................... 9170",
    "...................................................................... 9240",
    "...................................................................... 9310",
    "...................................................................... 9380",
    "...................................................................... 9450",
    "...................................................................... 9520",
    "...................................................................... 9590",
    "...................................................................... 9660",
    "...................................................................... 9730",
    "...................................................................... 9800",
    "...................................................................... 9870",
    ".....P................................................................ 9940",
    "........................................P........P.................... 10010",
    ".......................................P........P..................... 10080",
    ".......................P.........P.................................... 10150",
    "...................................................................... 10220",
    "...................................................................... 10290",
    "...................................................................... 10360",
    "...................................................................... 10430",
    "...................................................................... 10500",
    ".....................................................P................ 10570",
    "..........................F",
    "--- Failed steps:",
    "001 Scenario: I want to list the front app versions as an admin # features/FrontAppVersion/listFrontAppVersion.feature:48",
    "      And response content should be sorted by createdAt ASC    # features/FrontAppVersion/listFrontAppVersion.feature:52",
    "        Failed asserting that 1546300800 is equal to 1683640819 or is greater than 1683640819.",
    "--- Pending steps:",
    "001 Scenario: Add a coordinate correction as a writer to a question that he's the author # features/Correction/addCoordinateCorrection.feature:137",
    '      And "correction image recognition" correction read model should have:              # App\\Tests\\Behat\\Core\\Http\\Correction\\ReadModel\\CorrectionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Correction.",
    "002 Scenario: Add a coordinate correction as a writer to a question that he's the author without coordinates # features/Correction/addCoordinateCorrection.feature:161",
    '      And "correction image recognition" correction read model should have:                                  # App\\Tests\\Behat\\Core\\Http\\Correction\\ReadModel\\CorrectionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Correction.",
    "003 Scenario: Add a coordinate correction as a proof reader          # features/Correction/addCoordinateCorrection.feature:184",
    '      And "correction cardiology" correction read model should have: # App\\Tests\\Behat\\Core\\Http\\Correction\\ReadModel\\CorrectionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Correction.",
    "004 Scenario: Add a coordinate correction as a chief writer          # features/Correction/addCoordinateCorrection.feature:214",
    '      And "correction cardiology" correction read model should have: # App\\Tests\\Behat\\Core\\Http\\Correction\\ReadModel\\CorrectionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Correction.",
    "005 Scenario: Add a coordinate correction as a super admin           # features/Correction/addCoordinateCorrection.feature:244",
    '      And "correction cardiology" correction read model should have: # App\\Tests\\Behat\\Core\\Http\\Correction\\ReadModel\\CorrectionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Correction.",
    "006 Scenario: Add a coordinate correction as a chief writer to a question created by another writer # features/Correction/addCoordinateCorrection.feature:274",
    '      And "correction image recognition" correction read model should have:                         # App\\Tests\\Behat\\Core\\Http\\Correction\\ReadModel\\CorrectionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Correction.",
    "007 Scenario: Add a text correction as a writer to a question that he's the author # features/Correction/addTextCorrection.feature:123",
    '      And "correction image recognition" correction read model should have:        # App\\Tests\\Behat\\Core\\Http\\Correction\\ReadModel\\CorrectionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Correction.",
    "008 Scenario: Add a text correction as a proofreader                 # features/Correction/addTextCorrection.feature:147",
    '      And "correction cardiology" correction read model should have: # App\\Tests\\Behat\\Core\\Http\\Correction\\ReadModel\\CorrectionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Correction.",
    "009 Scenario: Add a text correction as a chief writer                # features/Correction/addTextCorrection.feature:187",
    '      And "correction cardiology" correction read model should have: # App\\Tests\\Behat\\Core\\Http\\Correction\\ReadModel\\CorrectionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Correction.",
    "010 Scenario: Add a text correction as a super admin                 # features/Correction/addTextCorrection.feature:227",
    '      And "correction cardiology" correction read model should have: # App\\Tests\\Behat\\Core\\Http\\Correction\\ReadModel\\CorrectionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Correction.",
    "011 Scenario: Add a text correction as a chief writer to a question from which he is not the author # features/Correction/addTextCorrection.feature:267",
    '      And "correction image recognition" correction read model should have:                         # App\\Tests\\Behat\\Core\\Http\\Correction\\ReadModel\\CorrectionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Correction.",
    "012 Example: | Sarah |                          # features/Correction/deleteCorrection.feature:88",
    '      And there is no correction "Correction 1" # App\\Tests\\Behat\\Core\\Http\\Correction\\ReadModel\\CorrectionDeletedContext::then()',
    "        waiting for 1368 story",
    "013 Example: | Jim   |                          # features/Correction/deleteCorrection.feature:89",
    '      And there is no correction "Correction 1" # App\\Tests\\Behat\\Core\\Http\\Correction\\ReadModel\\CorrectionDeletedContext::then()',
    "        waiting for 1368 story",
    "014 Scenario: Update a coordinate correction as a writer to a question that he is the author # features/Correction/updateCoordinateTypeCorrection.feature:109",
    '      And "correction question of mathieu" correction read model should have:                # App\\Tests\\Behat\\Core\\Http\\Correction\\ReadModel\\CorrectionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Correction.",
    "015 Example: | nathan     | nathan  |                                     # features/Correction/updateCoordinateTypeCorrection.feature:186",
    '      And "correction question-nathan" correction read model should have: # App\\Tests\\Behat\\Core\\Http\\Correction\\ReadModel\\CorrectionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Correction.",
    "016 Example: | nathan     | mathieu |                                      # features/Correction/updateCoordinateTypeCorrection.feature:187",
    '      And "correction question-mathieu" correction read model should have: # App\\Tests\\Behat\\Core\\Http\\Correction\\ReadModel\\CorrectionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Correction.",
    "017 Scenario: Update a priority correction as a writer to a question that he is the author # features/Correction/updateCorrectionPriority.feature:87",
    '      And "correction question of mathieu" correction read model should have:              # App\\Tests\\Behat\\Core\\Http\\Correction\\ReadModel\\CorrectionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Correction.",
    "018 Example: | nathan     | nathan  |                                     # features/Correction/updateCorrectionPriority.feature:159",
    '      And "correction question-nathan" correction read model should have: # App\\Tests\\Behat\\Core\\Http\\Correction\\ReadModel\\CorrectionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Correction.",
    "019 Example: | nathan     | mathieu |                                      # features/Correction/updateCorrectionPriority.feature:160",
    '      And "correction question-mathieu" correction read model should have: # App\\Tests\\Behat\\Core\\Http\\Correction\\ReadModel\\CorrectionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Correction.",
    "020 Scenario: Update a text correction as a writer to a question that he is the author # features/Correction/updateTextCorrection.feature:107",
    '      And "correction question of mathieu" correction read model should have:          # App\\Tests\\Behat\\Core\\Http\\Correction\\ReadModel\\CorrectionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Correction.",
    "021 Example: | nathan     | nathan  |                                     # features/Correction/updateTextCorrection.feature:167",
    '      And "correction question-nathan" correction read model should have: # App\\Tests\\Behat\\Core\\Http\\Correction\\ReadModel\\CorrectionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Correction.",
    "022 Example: | nathan     | mathieu |                                      # features/Correction/updateTextCorrection.feature:168",
    '      And "correction question-mathieu" correction read model should have: # App\\Tests\\Behat\\Core\\Http\\Correction\\ReadModel\\CorrectionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Correction.",
    "023 Example: | mathieu |                                                                                 # features/CorrectionStatementContent/addCorrectionStatementContentWithEmbedded.feature:162",
    '      And "correction content of image recognition" correction statement content read model should have: # App\\Tests\\Behat\\Core\\Http\\CorrectionStatementContent\\ReadModel\\CorrectionStatementContentContext::then()',
    "        waiting for 1369 story",
    "024 Example: | jammy   |                                                                                 # features/CorrectionStatementContent/addCorrectionStatementContentWithEmbedded.feature:163",
    '      And "correction content of image recognition" correction statement content read model should have: # App\\Tests\\Behat\\Core\\Http\\CorrectionStatementContent\\ReadModel\\CorrectionStatementContentContext::then()',
    "        waiting for 1369 story",
    "025 Example: | mathieu |                                                          # features/CorrectionStatementContent/addCorrectionStatementContentWithFile.feature:161",
    '      And "dummy correction" correction statement content read model should have: # App\\Tests\\Behat\\Core\\Http\\CorrectionStatementContent\\ReadModel\\CorrectionStatementContentContext::then()',
    "        waiting for 1369 story",
    "026 Example: | jammy   |                                                          # features/CorrectionStatementContent/addCorrectionStatementContentWithFile.feature:162",
    '      And "dummy correction" correction statement content read model should have: # App\\Tests\\Behat\\Core\\Http\\CorrectionStatementContent\\ReadModel\\CorrectionStatementContentContext::then()',
    "        waiting for 1369 story",
    "027 Example: | mathieu |                                              # features/CorrectionStatementContent/deleteCorrectionStatementContent.feature:103",
    '      And there is no "dummy correction" correction statement content # App\\Tests\\Behat\\Core\\Http\\CorrectionStatementContent\\ReadModel\\NoCorrectionStatementContentContext::then()',
    "        waiting for 1369 story",
    "028 Example: | jammy   |                                              # features/CorrectionStatementContent/deleteCorrectionStatementContent.feature:104",
    '      And there is no "dummy correction" correction statement content # App\\Tests\\Behat\\Core\\Http\\CorrectionStatementContent\\ReadModel\\NoCorrectionStatementContentContext::then()',
    "        waiting for 1369 story",
    "029 Scenario: Add course picture file as a Course Writer         # features/Course/addCoursePicture.feature:48",
    '      And "icon.png" course picture file read model should have: # App\\Tests\\Behat\\Core\\Http\\CoursePicture\\ReadModel\\CoursePictureContext::then()',
    "        No get route configured for course picture file",
    "030 Scenario: Delete a course picture as a course writer # features/Course/deleteCoursePicture.feature:48",
    '      And there is no "icon.png" course picture          # App\\Tests\\Behat\\Core\\Http\\CoursePicture\\ReadModel\\CoursePictureDeletedContext::then()',
    "        No get route configured for course picture file",
    "031 Scenario: Bookmark a course as a student                                  # features/CourseBookmark/bookmarkCourse.feature:56",
    '      And "student-1-course-bookmark" course bookmark read model should have: # App\\Tests\\Behat\\Core\\Http\\CourseBookmark\\ReadModel\\CourseBookmarkContext::then()',
    "        No get route configured for course bookmark",
    "032 Scenario: Add course content to a course as a course writer # features/CourseContent/addCourseContentToCourse.feature:127",
    '      And "mindmaps.pdf" course content read model should have: # App\\Tests\\Behat\\Core\\Http\\CourseContent\\ReadModel\\CourseContentContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Course\\CourseContent.",
    "033 Scenario: Delete my credential picture file as a Student # features/Credential/Picture/deleteMyCredentialPicture.feature:23",
    "      And there is no credential picture                     # App\\Tests\\Behat\\Core\\Http\\Credential\\ReadModel\\CredentialPictureDeletedContext::then()",
    "        No get route configured for credential picture file",
    "034 Scenario: Delete user credential picture  as a chief writer # features/Credential/Picture/deletePictureFromCredential.feature:47",
    "      And there is no credential picture                        # App\\Tests\\Behat\\Core\\Http\\Credential\\ReadModel\\CredentialPictureDeletedContext::then()",
    "        No get route configured for credential picture file",
    "035 Example: | mathieu |                                     # features/EcosAction/addEcosAction.feature:244",
    '      And "meal number?" ecos action read model should have: # App\\Tests\\Behat\\Core\\Http\\EcosAction\\ReadModel\\EcosActionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Ecos\\EcosAction.",
    "036 Example: | jammy   |                                     # features/EcosAction/addEcosAction.feature:245",
    '      And "meal number?" ecos action read model should have: # App\\Tests\\Behat\\Core\\Http\\EcosAction\\ReadModel\\EcosActionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Ecos\\EcosAction.",
    "037 Example: | mathieu |                                      # features/EcosSection/addEcosSection.feature:210",
    '      And "meal number?" ecos section read model should have: # App\\Tests\\Behat\\Core\\Http\\EcosSection\\ReadModel\\EcosSectionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Ecos\\EcosSection.",
    "038 Example: | jammy   |                                      # features/EcosSection/addEcosSection.feature:211",
    '      And "meal number?" ecos section read model should have: # App\\Tests\\Behat\\Core\\Http\\EcosSection\\ReadModel\\EcosSectionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Ecos\\EcosSection.",
    "039 Scenario: Add a new exam as a writer without dates # features/Exam/addExam.feature:78",
    '      And "Exam 1000" exam read model should have:     # App\\Tests\\Behat\\Core\\Http\\Exam\\ReadModel\\ExamContext::then()',
    "        waiting for 1877 story",
    "040 Scenario: Add a new exam as a writer           # features/Exam/addExam.feature:126",
    '      And "Exam 1000" exam read model should have: # App\\Tests\\Behat\\Core\\Http\\Exam\\ReadModel\\ExamContext::then()',
    "        waiting for 1877 story",
    "041 Scenario: Reschedule an exam as a chief writer # features/Exam/rescheduleExam.feature:59",
    '      And "radiology" exam read model should have: # App\\Tests\\Behat\\Core\\Http\\Exam\\ReadModel\\ExamContext::then()',
    "        waiting for 1877 story",
    "042 Example: | Lara |                                              # features/ExamContent/addExamContent.feature:222",
    '      And "some exam content" exam content read model should have: # App\\Tests\\Behat\\Core\\Http\\ExamContent\\ReadModel\\ExamContentContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamContent.",
    "043 Example: | Sam  |                                              # features/ExamContent/addExamContent.feature:223",
    '      And "some exam content" exam content read model should have: # App\\Tests\\Behat\\Core\\Http\\ExamContent\\ReadModel\\ExamContentContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamContent.",
    "044 Example: | Luc  |                                              # features/ExamContent/addExamContent.feature:224",
    '      And "some exam content" exam content read model should have: # App\\Tests\\Behat\\Core\\Http\\ExamContent\\ReadModel\\ExamContentContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamContent.",
    "045 Example: | writer |                                                   # features/ExamContent/updateExamContent.feature:153",
    '      And "dermatology content exam" exam content read model should have: # App\\Tests\\Behat\\Core\\Http\\ExamContent\\ReadModel\\ExamContentContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamContent.",
    "046 Example: | Sam    |                                                   # features/ExamContent/updateExamContent.feature:154",
    '      And "dermatology content exam" exam content read model should have: # App\\Tests\\Behat\\Core\\Http\\ExamContent\\ReadModel\\ExamContentContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamContent.",
    "047 Example: | Sarah     |                                                             # features/ExamContent/updateExamContentPriority.feature:118",
    '      And "exam content of exam created by Sarah" exam content read model should have: # App\\Tests\\Behat\\Core\\Http\\ExamContent\\ReadModel\\ExamContentContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamContent.",
    "048 Example: | Jim       |                                                             # features/ExamContent/updateExamContentPriority.feature:119",
    '      And "exam content of exam created by Sarah" exam content read model should have: # App\\Tests\\Behat\\Core\\Http\\ExamContent\\ReadModel\\ExamContentContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamContent.",
    "049 Example: | mathieu |                                                   # features/ExamContentCourse/addExamContentCourse.feature:223",
    '      And "Contenu d\'un cours" exam content course read model should have: # App\\Tests\\Behat\\Core\\Http\\ExamContentCourse\\ReadModel\\ExamContentCourseContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamContentCourse.",
    "050 Example: | eric    |                                                   # features/ExamContentCourse/addExamContentCourse.feature:224",
    '      And "Contenu d\'un cours" exam content course read model should have: # App\\Tests\\Behat\\Core\\Http\\ExamContentCourse\\ReadModel\\ExamContentCourseContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamContentCourse.",
    "051 Scenario: Consult an exam content course as a student                          # features/ExamContentCourse/consultExamContentCourse.feature:50",
    '      And "Les maladies aortiques - 1" exam content course read model should have: # App\\Tests\\Behat\\Core\\Http\\ExamContentCourse\\ReadModel\\ExamContentCourseContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamContentCourse.",
    "052 Example: | mathieu |                                                                 # features/ExamContentCourse/updateExamContentCourse.feature:198",
    '      And "les maladies dermatologiques - 1" exam content course read model should have: # App\\Tests\\Behat\\Core\\Http\\ExamContentCourse\\ReadModel\\ExamContentCourseContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamContentCourse.",
    "053 Example: | jammy   |                                                                 # features/ExamContentCourse/updateExamContentCourse.feature:199",
    '      And "les maladies dermatologiques - 1" exam content course read model should have: # App\\Tests\\Behat\\Core\\Http\\ExamContentCourse\\ReadModel\\ExamContentCourseContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamContentCourse.",
    "054 Example: | mathieu |                                             # features/ExamContentEcos/addExamContentEcos.feature:294",
    '      And "Ecos patient 1" exam content ecos read model should have: # App\\Tests\\Behat\\Core\\Http\\ExamContentEcos\\ReadModel\\ExamContentEcosContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamContentEcos.",
    "055 Example: | jammy   |                                             # features/ExamContentEcos/addExamContentEcos.feature:295",
    '      And "Ecos patient 1" exam content ecos read model should have: # App\\Tests\\Behat\\Core\\Http\\ExamContentEcos\\ReadModel\\ExamContentEcosContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamContentEcos.",
    "056 Example: | Sarah     |                              # features/ExamContentQuestion/addExamContentQuestion.feature:179",
    "      And exam content question read model should have: # App\\Tests\\Behat\\Core\\Http\\ExamContentQuestion\\ReadModel\\ExamContentQuestionContext::then()",
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamContentQuestion.",
    "057 Example: | Jim       |                              # features/ExamContentQuestion/addExamContentQuestion.feature:180",
    "      And exam content question read model should have: # App\\Tests\\Behat\\Core\\Http\\ExamContentQuestion\\ReadModel\\ExamContentQuestionContext::then()",
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamContentQuestion.",
    "058 Example: | Sarah     |                              # features/ExamContentQuestion/updateExamContentQuestionPriority.feature:132",
    "      And exam content question read model should have: # App\\Tests\\Behat\\Core\\Http\\ExamContentQuestion\\ReadModel\\ExamContentQuestionContext::then()",
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamContentQuestion.",
    "059 Example: | Jim       |                              # features/ExamContentQuestion/updateExamContentQuestionPriority.feature:133",
    "      And exam content question read model should have: # App\\Tests\\Behat\\Core\\Http\\ExamContentQuestion\\ReadModel\\ExamContentQuestionContext::then()",
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamContentQuestion.",
    "060 Scenario: Rate exam content as a student                                        # features/ExamContentRate/rateExamContent.feature:91",
    '      And exam content "dummy exam content" rated by "Lara" read model should have: # App\\Tests\\Behat\\Core\\Http\\ExamContentRate\\ReadModel\\ExamContentRateContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Rate\\ExamContentRate.",
    "061 Scenario: Add an exam group with a valid exam publication status as a chief writer # features/ExamGroup/addExamGroup.feature:155",
    '      And "multirank 1" exam group read model should have:                             # App\\Tests\\Behat\\Core\\Http\\ExamGroup\\ReadModel\\ExamGroupContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamGroup.",
    "062 Scenario: Reschedule exam group as a chief writer      # features/ExamGroup/rescheduleExamGroup.feature:79",
    '      And "multirank 1" exam group read model should have: # App\\Tests\\Behat\\Core\\Http\\ExamGroup\\ReadModel\\ExamGroupContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamGroup.",
    "063 Scenario: Update an exam group as a chief writer       # features/ExamGroup/updateExamGroup.feature:86",
    '      And "multirank 1" exam group read model should have: # App\\Tests\\Behat\\Core\\Http\\ExamGroup\\ReadModel\\ExamGroupContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamGroup.",
    "064 Example: | READY_FOR_PUBLICATION    | DRAFT                 | # features/ExamGroup/updateExamGroupPublicationStatus.feature:105",
    '      And "exam group" exam group read model should have:         # App\\Tests\\Behat\\Core\\Http\\ExamGroup\\ReadModel\\ExamGroupContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamGroup.",
    "065 Example: | PUBLISHED                | DRAFT                 | # features/ExamGroup/updateExamGroupPublicationStatus.feature:106",
    '      And "exam group" exam group read model should have:         # App\\Tests\\Behat\\Core\\Http\\ExamGroup\\ReadModel\\ExamGroupContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamGroup.",
    "066 Example: | DRAFT                    | READY_FOR_PUBLICATION | # features/ExamGroup/updateExamGroupPublicationStatus.feature:107",
    '      And "exam group" exam group read model should have:         # App\\Tests\\Behat\\Core\\Http\\ExamGroup\\ReadModel\\ExamGroupContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamGroup.",
    "067 Example: | PUBLISHED                | READY_FOR_PUBLICATION | # features/ExamGroup/updateExamGroupPublicationStatus.feature:108",
    '      And "exam group" exam group read model should have:         # App\\Tests\\Behat\\Core\\Http\\ExamGroup\\ReadModel\\ExamGroupContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamGroup.",
    "068 Example: | READY_FOR_PUBLICATION    | PUBLISHED             | # features/ExamGroup/updateExamGroupPublicationStatus.feature:109",
    '      And "exam group" exam group read model should have:         # App\\Tests\\Behat\\Core\\Http\\ExamGroup\\ReadModel\\ExamGroupContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Exam\\ExamGroup.",
    "069 Scenario: Student answer a feedback                             # features/FeedbackAnswer/addStudentFeedbackAnswer.feature:74",
    '      And "answer-feedback" feedback answer read model should have: # App\\Tests\\Behat\\Core\\Http\\FeedbackAnswer\\ReadModel\\FeedbackAnswerContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\FeedbackAnswer.",
    "070 Scenario: Mark feedback answer as read as a student author of the feedback           # features/FeedbackAnswer/markFeedbackAnswerAsRead.feature:63",
    '      And "Answer of dependency course feedback" feedback answer read model should have: # App\\Tests\\Behat\\Core\\Http\\FeedbackAnswer\\ReadModel\\FeedbackAnswerContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\FeedbackAnswer.",
    "071 Example: | Jim        | Course feedback added by Lara for Jim   | # features/FeedbackAnswer/writerAddFeedbackAnswer.feature:143",
    '      And "answer-feedback" feedback answer read model should have:   # App\\Tests\\Behat\\Core\\Http\\FeedbackAnswer\\ReadModel\\FeedbackAnswerContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\FeedbackAnswer.",
    "072 Example: | Sarah      | Course feedback added by Lara for Sarah | # features/FeedbackAnswer/writerAddFeedbackAnswer.feature:144",
    '      And "answer-feedback" feedback answer read model should have:   # App\\Tests\\Behat\\Core\\Http\\FeedbackAnswer\\ReadModel\\FeedbackAnswerContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\FeedbackAnswer.",
    "073 Example: | Thomas     | Course feedback added by Lara for Sarah | # features/FeedbackAnswer/writerAddFeedbackAnswer.feature:145",
    '      And "answer-feedback" feedback answer read model should have:   # App\\Tests\\Behat\\Core\\Http\\FeedbackAnswer\\ReadModel\\FeedbackAnswerContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\FeedbackAnswer.",
    "074 Scenario: Rate folder as a Student                                  # features/FolderRate/rateFolder.feature:89",
    '      And folder "dummy folder" rated by "Lara" read model should have: # App\\Tests\\Behat\\Core\\Http\\FolderRate\\ReadModel\\FolderRateContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\Rate\\FolderRate.",
    "075 Example: | mathieu |                                                                     # features/FolderStatementContent/addEmbeddedFolderStatementContent.feature:138",
    '      And "dummy embedded folder statement" folder statement content read model should have: # App\\Tests\\Behat\\Core\\Http\\FolderStatementContent\\ReadModel\\FolderStatementContentContext::then()',
    "        waiting for 1248 story",
    "076 Example: | jammy   |                                                                     # features/FolderStatementContent/addEmbeddedFolderStatementContent.feature:139",
    '      And "dummy embedded folder statement" folder statement content read model should have: # App\\Tests\\Behat\\Core\\Http\\FolderStatementContent\\ReadModel\\FolderStatementContentContext::then()',
    "        waiting for 1248 story",
    "077 Example: | mathieu |                                                                 # features/FolderStatementContent/addFileFolderStatementContent.feature:148",
    '      And "dummy file folder statement" folder statement content read model should have: # App\\Tests\\Behat\\Core\\Http\\FolderStatementContent\\ReadModel\\FolderStatementContentContext::then()',
    "        waiting for 1248 story",
    "078 Example: | jammy   |                                                                 # features/FolderStatementContent/addFileFolderStatementContent.feature:149",
    '      And "dummy file folder statement" folder statement content read model should have: # App\\Tests\\Behat\\Core\\Http\\FolderStatementContent\\ReadModel\\FolderStatementContentContext::then()',
    "        waiting for 1248 story",
    "079 Example: | mathieu |                                      # features/FolderStatementContent/deleteFolderStatementContent.feature:103",
    '      And there is no "dummy folder" folder statement content # App\\Tests\\Behat\\Core\\Http\\FolderStatementContent\\ReadModel\\NoFolderStatementContentContext::then()',
    "        waiting for 1248 story",
    "080 Example: | jammy   |                                      # features/FolderStatementContent/deleteFolderStatementContent.feature:104",
    '      And there is no "dummy folder" folder statement content # App\\Tests\\Behat\\Core\\Http\\FolderStatementContent\\ReadModel\\NoFolderStatementContentContext::then()',
    "        waiting for 1248 story",
    "081 Scenario: Add front app version as an ecni admin         # features/FrontAppVersion/addFrontAppVersion.feature:72",
    '      And "v3.6.9" front app version read model should have: # App\\Tests\\Behat\\Core\\Http\\FrontAppVersion\\ReadModel\\FrontAppVersionContext::then()',
    "        No get route configured for resource App\\Core\\Domain\\Entity\\FrontAppVersion.",
    "1148 scenarios (1066 passed, 1 failed, 81 pending)",
    "10597 steps (10500 passed, 1 failed, 81 pending, 15 skipped)",
    "3m55.98s (198.10Mb)",
    "make: *** [Makefile.test:111: behat-http] Error 1",
    "ERROR: Job failed: exit code 1",
];

console.log(getFeatureFiles(data));
